server:
  port: 8885


spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:dm://192.168.0.246:5236/SMZ_FROM_ORACLE?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: SMZ_FROM_ORACLE
          password: Cqsmz.123
          driver-class-name: dm.jdbc.driver.DmDriver
        oracle:
          url: jdbc:oracle:thin:@172.18.40.200:1521:smz?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: ZBBSMZ
          password: 123456
          driver-class-name: oracle.jdbc.driver.OracleDriver
  # 连接池
  hikari:
    #连接池名
    pool-name: DateHikariCP
    #最小空闲连接数
    minimum-idle: 5
    # 空闲连接存活最大时间，默认600000（10分钟）
    idle-timeout: 180000
    # 连接池最大连接数，默认是10
    maximum-pool-size: 1000
    # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
    auto-commit: true
    # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    max-lifetime: 0
    # 数据库连接超时时间,默认30秒，即30000
    connection-timeout: 180000
    connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    #    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml
  level:
    top.tanmw.oracle2dm.dao: debug

com:
  efficient:
    change-field-length: false
    update-filed-length-map:
      DAIMA: DWMC,YDBM
      ZJ_WJYS: WJMC
      DFPBZLX: DFPBZLX_DESP
      GBP_USER_BEFORMD5: REALNAME
      JDXZ_BD: BEIZHU
      JJJ: YDBM
      LOCAL_BD: BEIZHU
      LXFS: LXFS_LXR
      REPORT_JGSY_COMMON: JGSY_NAME
      REPORT_SY: INCORPORATOR,JGBZWH
      REPORT_T_BWRY_JBXX: XM
      SY: INCORPORATOR
      ZHXSH: DESP
    identityList:
      - GBP_USER
      - GBP_ROLE
      - GBP_ROLEMENU
      - ZJ_WJYS
    skipList:
      - DICTTREE_LIB
      - DICTT_LIBMAPPING
      - DICT_CODE_LIB
      - LIB_MANAGER
      - GBP_MENU_SANYUAN
    # 批量保存数量
    batch-save-size: 50000
    # 需要分页的数量，100万
    need-page: 1000000
    # 分页查询的，100万
    page-size: 200000



